name: Delete Old Dead Flowers (Daily)

on:
  schedule:
    - cron: '0 3 * * *'  # Every day at 3:00 AM UTC
  workflow_dispatch:

jobs:
  call-function:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Supabase function
        run: |
          curl -X POST "${{ secrets.SUPABASE_PROJECT_URL }}/functions/v1/delete_old_dead_flowers" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}"
